### ISSUE TITLE
mccs-alpha-api, two dead links

### ISSUE THREAD

**Issue by konfib** [ic3software/mccs#4]
Hi,
under: https://github.com/ic3software/mccs-alpha-api

the two api links at  swaggerhub.com are not working anymore.
**API Documentation**
[User API](https://app.swaggerhub.com/apis-docs/ic3network/mccs-alpha-user-api/1) » https://app.swaggerhub.com/apis-docs/ic3network/mccs-alpha-user-api/1 «
[Admin API](https://app.swaggerhub.com/apis-docs/ic3network/mccs-alpha-admin-api/1) » https://app.swaggerhub.com/apis-docs/ic3network/mccs-alpha-admin-api/1 «

**Comment by geoffturk** [comment]
Thanks for flagging this. The links have been fixed.
